"""start

Revision ID: a44bed8ce055
Revises: 
Create Date: 2024-11-13 16:17:44.833809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a44bed8ce055"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_company",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_company_code"), "stock_company", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_stock_company_created_at"),
        "stock_company",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_company_name"), "stock_company", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_stock_company_updated_at"),
        "stock_company",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "stock",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_company_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("purchased_amount", sa.Integer(), nullable=False),
        sa.Column("purchased_status", sa.String(), nullable=False),
        sa.Column("request_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_company_id"],
            ["stock_company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_created_at"), "stock", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_stock_request_date"), "stock", ["request_date"], unique=False
    )
    op.create_index(op.f("ix_stock_updated_at"), "stock", ["updated_at"], unique=False)
    op.create_table(
        "competitor",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("stock_company_id", sa.Integer(), nullable=False),
        sa.Column(
            "company_name",
            sa.String(),
            nullable=True,
            comment="No caso de não identificar o stock_company_id",
        ),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_company_id"],
            ["stock_company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stock.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_competitor_created_at"), "competitor", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_competitor_updated_at"), "competitor", ["updated_at"], unique=False
    )
    op.create_table(
        "performance_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("five_days", sa.Float(), nullable=False),
        sa.Column("one_month", sa.Float(), nullable=False),
        sa.Column("three_months", sa.Float(), nullable=False),
        sa.Column("year_to_date", sa.Float(), nullable=False),
        sa.Column("one_year", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stock.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_performance_data_created_at"),
        "performance_data",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_performance_data_updated_at"),
        "performance_data",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "stock_values",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stock.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_values_created_at"), "stock_values", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_stock_values_updated_at"), "stock_values", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_values_updated_at"), table_name="stock_values")
    op.drop_index(op.f("ix_stock_values_created_at"), table_name="stock_values")
    op.drop_table("stock_values")
    op.drop_index(op.f("ix_performance_data_updated_at"), table_name="performance_data")
    op.drop_index(op.f("ix_performance_data_created_at"), table_name="performance_data")
    op.drop_table("performance_data")
    op.drop_index(op.f("ix_competitor_updated_at"), table_name="competitor")
    op.drop_index(op.f("ix_competitor_created_at"), table_name="competitor")
    op.drop_table("competitor")
    op.drop_index(op.f("ix_stock_updated_at"), table_name="stock")
    op.drop_index(op.f("ix_stock_request_date"), table_name="stock")
    op.drop_index(op.f("ix_stock_created_at"), table_name="stock")
    op.drop_table("stock")
    op.drop_index(op.f("ix_stock_company_updated_at"), table_name="stock_company")
    op.drop_index(op.f("ix_stock_company_name"), table_name="stock_company")
    op.drop_index(op.f("ix_stock_company_created_at"), table_name="stock_company")
    op.drop_index(op.f("ix_stock_company_code"), table_name="stock_company")
    op.drop_table("stock_company")
    # ### end Alembic commands ###
