"""log de request e response

Revision ID: d3dcf8822b91
Revises: a44bed8ce055
Create Date: 2024-11-13 20:25:31.697623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3dcf8822b91'
down_revision: Union[str, None] = 'a44bed8ce055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('log_request_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=250), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('function_name', sa.String(length=100), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('requester', sa.JSON(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_request_id')
    )
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_updated_at'), 'logs', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_updated_at'), table_name='logs')
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
