CREATE DATABASE airflow;
CREATE DATABASE redis;
CREATE DATABASE sonar;
CREATE DATABASE snatcher;

GRANT ALL PRIVILEGES ON DATABASE airflow TO admin;
GRANT ALL PRIVILEGES ON DATABASE redis TO admin;
GRANT ALL PRIVILEGES ON DATABASE sonar TO admin;
